name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libz-dev \
            openjdk-11-jdk \
            unzip \
            zip \
            zlib1g-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-venv \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libmtdev-dev \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libpulse-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libgl1

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.33 buildozer==1.5.0

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: First Build to Trigger SDK Download
        run: |
          buildozer android clean || true
          buildozer android debug || true

      - name: Manually Download Android cmdline-tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Accept Licenses & Install Build-Tools
        run: |
          export SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$SDK_ROOT/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses
          sdkmanager "build-tools;36.0.0"

      - name: Final APK Build
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
