name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential ccache git zip unzip openjdk-8-jdk python3-pip \
            libncurses5 libstdc++6 libgtk2.0-0 libpangox-1.0-0 \
            libpangoxft-1.0-0 libidn11 libpython3-dev
          pip install --upgrade pip setuptools cython
          pip install buildozer

      - name: Get Date
        id: get-date
        run: echo "date=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Cache .buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build Android APK
        run: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: bin/*.apk
