name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libz-dev \
            openjdk-11-jdk \
            unzip \
            zip \
            zlib1g-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-venv \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libmtdev-dev \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libpulse-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libgl1

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.33 buildozer==1.5.0

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Prewarm Buildozer & Accept Licenses
        run: |
          buildozer android clean || true
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0"

      - name: Build the APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
